import { useState } from 'react'
import { UserPlus, Shield, Mail, Check, KeyRound, Send } from 'lucide-react'
import type { AuthResponse } from '../types/models'
import { api as authApi } from '../api/client'
import type { WorkspaceApi } from './api'
import { useAction, useRemote } from './api'
import type { Mail as MailItem, Member, Subscription } from './types'
import { date, label, roleNames, roles } from './types'
import { Feedback, SectionHead } from './ui'

export function MembersPanel({ api }: { api: WorkspaceApi }) {
  const members = useRemote<Member[]>(api, '/members', [])
  const action = useAction()
  const [email, setEmail] = useState('')
  const [role, setRole] = useState('STUDENT')
  const [invitation, setInvitation] = useState('')
  return <section className="ws-section"><SectionHead title="Членове и роли" /><Feedback error={members.error || action.error} message={action.message} busy={action.busy} />
    <form className="ws-inline-form" onSubmit={e => { e.preventDefault(); void action.run(async () => { const result = await api.post<{ token: string }>('/invitations', { email, roles: [role], groupId: null }); setInvitation(result.token) }) }}><label>Имейл<input type="email" required value={email} onChange={e => setEmail(e.target.value)} /></label><label>Роля<select value={role} onChange={e => setRole(e.target.value)}>{Object.entries(roleNames).map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label><button disabled={action.busy}><UserPlus size={17} /> Покани</button></form>{invitation && <label>Еднократен токен<input readOnly value={invitation} /></label>}
    <div className="ws-table-wrap"><table className="ws-table"><thead><tr><th>Потребител</th><th>Имейл</th><th>Роли в организацията</th><th>Статус</th></tr></thead><tbody>{members.data.map(m => <tr key={m.user_id}><td>{m.name}</td><td>{m.email}</td><td><div className="ws-role-checks">{Object.entries(roleNames).map(([key, text]) => <label className="ws-check" key={key}><input type="checkbox" checked={roles(m).includes(key)} disabled={action.busy} onChange={e => void action.run(async () => { const next = e.target.checked ? [...roles(m), key] : roles(m).filter(r => r !== key); await api.put(`/members/${m.user_id}`, { roles: next, active: m.status === 'active' }); await members.reload() })} />{text}</label>)}</div></td><td><button disabled={action.busy} onClick={() => void action.run(async () => { await api.put(`/members/${m.user_id}`, { roles: roles(m), active: m.status !== 'active' }); await members.reload() })}>{label(m.status)}</button></td></tr>)}</tbody></table></div>
  </section>
}
export function BillingPanel({ api, admin }: { api: WorkspaceApi; admin: boolean }) {
  const billing = useRemote<Subscription | null>(api, '/billing', null)
  return <section className="ws-section"><SectionHead title="Абонамент на организацията" /><Feedback error={billing.error} busy={billing.loading} />{billing.data && <><dl className="ws-billing"><dt>План</dt><dd>{billing.data.plan_name}</dd><dt>Статус</dt><dd>{label(billing.data.status)}</dd><dt>Достъп до</dt><dd>{date(billing.data.paid_through)}</dd><dt>Активни учители</dt><dd>До {billing.data.teacher_limit}</dd><dt>Активни обучаеми</dt><dd>До {billing.data.student_limit}</dd><dt>AI за периода</dt><dd>{billing.data.ai_used} използвани · {billing.data.ai_reserved} резервирани / {billing.data.ai_limit}</dd><dt>Примерни цени</dt><dd>{billing.data.monthly_eur} EUR / месец · {billing.data.yearly_eur} EUR / година</dd></dl>{billing.data.demonstration && <p className="ws-notice">Демонстрационни цени. Не са одобрена търговска оферта.</p>}<p>Абонаментът е организационен. Обучаемите не заплащат отделни опити.</p></>}{admin && <BillingCheckout api={api} />}</section>
}
export function WorkspaceProfile({ api, auth, onAuth }: { api: WorkspaceApi; auth: AuthResponse; onAuth: (next: AuthResponse) => void }) {
  const address = useRemote<{ email: string; verified_at: string | null } | null>(api, '/profile/notification-email', null)
  const mailbox = useRemote<MailItem[]>(api, '/profile/mailbox', [])
  const action = useAction()
  const [email, setEmail] = useState(auth.user.email)
  const google = useRemote<{ enabled: boolean } | null>(api, '/api/auth/google/config', null)
  const [password, setPassword] = useState('')
  const [newPassword, setNewPassword] = useState('')
  const [invite, setInvite] = useState(() => new URLSearchParams(window.location.hash.slice(1)).get('invitation') ?? '')
  const [verification, setVerification] = useState(() => window.location.pathname.startsWith('/verify-email') ? new URLSearchParams(window.location.search).get('token') ?? '' : '')
  const identities = useRemote<{ provider: string; linked_at: string }[]>(api, '/profile/identities', [])
  return <section className="ws-section"><SectionHead title="Моят профил" /><Feedback error={action.error || address.error} message={action.message} busy={action.busy} /><h3><Mail size={17} /> Имейл за известия</h3>{address.data && <p>{address.data.email} · {address.data.verified_at ? 'Потвърден' : 'Непотвърден'}</p>}
    <form className="ws-inline-form" onSubmit={e => { e.preventDefault(); void action.run(async () => { await api.post('/profile/notification-email', { email, password }); await mailbox.reload() }, 'Изпратено е потвърждение до новия адрес.') }}><label>Нов адрес<input type="email" required value={email} onChange={e => setEmail(e.target.value)} /></label><label>Текуща парола<input type="password" required autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} /></label><button disabled={action.busy}><Send size={17} /> Потвърди адреса</button></form>
    {verification && <button onClick={() => void action.run(async () => { await api.post('/profile/notification-email/verify', { token: verification }); await address.reload(); setVerification(''); history.replaceState(null, '', '/') }, 'Имейлът е потвърден.')}><Check size={17} /> Потвърди адреса от линка</button>}
    <h3><KeyRound size={17} /> Нова парола</h3><form className="ws-inline-form" onSubmit={e => { e.preventDefault(); void action.run(async () => { const next = await authApi.changePassword(auth.token, password, newPassword); setPassword(''); setNewPassword(''); onAuth(next) }) }}><label>Текуща парола<input type="password" required value={password} onChange={e => setPassword(e.target.value)} /></label><label>Нова парола<input type="password" required minLength={8} maxLength={72} value={newPassword} onChange={e => setNewPassword(e.target.value)} /></label><button disabled={action.busy}><KeyRound size={17} /> Смени и прекрати старите сесии</button></form>
    <button onClick={() => void action.run(async () => { await authApi.logoutAll(auth.token); window.dispatchEvent(new CustomEvent('quicktest:session-expired', { detail: auth.token })) })}><Shield size={17} /> Изход от всички сесии</button><h3>Свързан Google профил</h3>{identities.data.map(i => <p key={i.provider}>{i.provider} · {date(i.linked_at)}</p>)}<form className="ws-inline-form" onSubmit={e => { e.preventDefault(); void action.run(async () => { const result = await api.post<{ url: string }>('/profile/google/link', { password }); window.location.assign(result.url) }) }}><label>Парола за повторно удостоверяване<input type="password" required value={password} onChange={e => setPassword(e.target.value)} /></label><button disabled={action.busy || !google.data?.enabled}>Свържи Google акаунт{google.data && !google.data.enabled ? ' (не е конфигуриран)' : ''}</button></form>
    <h3><UserPlus size={17} /> Приеми покана</h3><form className="ws-inline-form" onSubmit={e => { e.preventDefault(); void action.run(async () => { await api.post('/invitations/accept', { token: invite }); window.dispatchEvent(new Event('examai:organizations-refresh')); setInvite(''); history.replaceState(null, '', '/') }, 'Поканата е приета.') }}><label>Токен<input required value={invite} onChange={e => setInvite(e.target.value)} /></label><button disabled={action.busy}>Приеми</button></form>
    {!mailbox.error && <><h3><Shield size={17} /> Локална тестова пощенска кутия</h3><div className="ws-table-wrap"><table className="ws-table"><thead><tr><th>Дата</th><th>До</th><th>Вид</th><th>Статус</th><th>Действие</th></tr></thead><tbody>{mailbox.data.map(item => { const payload = JSON.parse(item.payload_json) as { token?: string; test?: string; grade?: string; outcome?: string }; return <tr key={item.id}><td>{date(item.created_at)}</td><td>{item.recipient_email}</td><td>{item.notification_type === 'notification_email' ? 'Потвърждение' : item.notification_type === 'final_result' ? `${payload.test} · оценка ${payload.grade}` : item.notification_type}</td><td>{label(item.status)}</td><td>{item.notification_type === 'notification_email' && payload.token && <button title="Потвърди имейла" className="command-button" onClick={() => void action.run(async () => { await api.post('/profile/notification-email/verify', { token: payload.token }); await address.reload() }, 'Имейлът е потвърден.')}><Check size={16} /> Потвърди</button>}</td></tr> })}</tbody></table></div></>}
  </section>
}

function BillingCheckout({ api }: { api: WorkspaceApi }) {
  const config = useRemote<{ mode: string } | null>(api, '/billing/config', null)
  const plans = useRemote<{ id: number; name: string }[]>(api, '/plans', [])
  const history = useRemote<{ event_id: string; provider: string; status: string; created_at: string }[]>(api, '/billing/history', [])
  const action = useAction()
  const [plan, setPlan] = useState(''), [period, setPeriod] = useState('month')
  return <><h3>Плащане в тестова среда</h3><button disabled={action.busy || config.data?.mode !== 'stripe_test'} onClick={() => void action.run(async () => { const value = await api.post<{ url: string }>('/billing/portal'); window.location.assign(value.url) })}>Управление / прекратяване / документи</button><Feedback error={action.error || history.error} /><form className="ws-inline-form" onSubmit={e => { e.preventDefault(); void action.run(async () => { const value = await api.post<{ url: string }>('/billing/checkout', { planId: Number(plan), period, requestKey: crypto.randomUUID() }); window.location.assign(value.url) }) }}><label>План<select required value={plan} onChange={e => setPlan(e.target.value)}><option value="">Избери</option>{plans.data.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Период<select value={period} onChange={e => setPeriod(e.target.value)}><option value="month">Месечен</option><option value="year">Годишен</option></select></label><button disabled={action.busy || config.data?.mode !== 'stripe_test'}>Stripe test{config.data?.mode === 'unconfigured' ? ' (не е конфигуриран)' : ''}</button></form><div className="ws-table-wrap"><table className="ws-table"><thead><tr><th>Дата</th><th>Събитие</th><th>Доставчик</th><th>Статус</th></tr></thead><tbody>{history.data.map(e => <tr key={e.event_id}><td>{date(e.created_at)}</td><td>{e.event_id}</td><td>{e.provider}</td><td>{label(e.status)}</td></tr>)}</tbody></table></div></>
}
