import { useEffect, useState } from 'react'
import { Plus, Save, Send, Trash2, Copy, Sparkles, ArrowLeft, X, Check, Library } from 'lucide-react'
import { useAction, useRemote } from './api'
import type { WorkspaceApi } from './api'
import type { AiJob, Assessment, Definition, Question, QuestionType } from './types'
import { date, label } from './types'
import { Empty, Feedback, SectionHead } from './ui'
import { WorkspaceImage } from './WorkspaceImage'
import { imageBase64 } from './imageUpload'

const question = (): Question => ({ type: 'SINGLE_CHOICE', text: '', difficulty: 'MEDIUM', points: 1, timeSeconds: 60, options: [{ text: '', correct: true }, { text: '', correct: false }], acceptedAnswers: [], caseInsensitive: true, collapseWhitespace: true, criteria: '', explanation: '' })
const blank = (): Definition => ({ title: 'Нов тест', description: '', subject: '', level: '', instructions: '', language: 'bg', gradingScale: 'bulgarian', passThreshold: 50, questions: [question()] })
const types: [QuestionType, string][] = [['SINGLE_CHOICE', 'Един верен отговор'], ['MULTIPLE_CHOICE', 'Няколко верни'], ['TRUE_FALSE', 'Вярно / невярно'], ['SHORT_ANSWER', 'Кратък текст'], ['OPEN_ANSWER', 'Свободен отговор']]

export function AssessmentEditor({ api, userId }: { api: WorkspaceApi; userId: number }) {
  const list = useRemote<Assessment[]>(api, '/tests', [])
  const action = useAction()
  const bank = useRemote<{ id: number; owner_id: number; subject: string; shared: boolean; definition_json: string }[]>(api, '/question-bank', [])
  const [bankItem, setBankItem] = useState('')
  const [selectedQuestions, setSelectedQuestions] = useState<number[]>([])
  const [replacements, setReplacements] = useState<number[]>([])
  const [aiSubject, setAiSubject] = useState(''), [aiLevel, setAiLevel] = useState(''), [aiLanguage, setAiLanguage] = useState('bg')
  const [aiTypes, setAiTypes] = useState<string[]>(['SINGLE_CHOICE'])
  const [distribution, setDistribution] = useState<Record<string, number>>({ EASY: 2, MEDIUM: 2, HARD: 1, VERY_HARD: 0 })
  function reviewJob() {
    if (!job?.result_json) return
    const definition = (JSON.parse(job.result_json) as { definition: Definition }).definition
    if (draft && replacements.length) setDraft({ ...draft, questions: draft.questions.map((q, i) => { const replacement = replacements.indexOf(i); return replacement < 0 ? q : definition.questions[replacement] }) })
    else { setCurrent(null); setDraft(definition) }
    setReplacements([]); setSelectedQuestions([]); setJob(null)
  }
  const [current, setCurrent] = useState<Assessment | null>(null)
  const [draft, setDraft] = useState<Definition | null>(null)
  const [pendingDelete, setPendingDelete] = useState<Assessment | null>(null)
  const [topic, setTopic] = useState('Основи на Java')
  const [count, setCount] = useState(5)
  const [difficulty, setDifficulty] = useState('MEDIUM')
  const [source, setSource] = useState('')
  const [job, setJob] = useState<AiJob | null>(null)
  const editable = !current || current.owner_id === userId

  useEffect(() => {
    if (!job || !['queued', 'running'].includes(job.status)) return
    const timer = window.setInterval(() => {
      api.get<AiJob>(`/ai/test-generations/${job.id}`).then(setJob).catch(() => { /* The job remains resumable on reconnect. */ })
    }, 2000)
    return () => window.clearInterval(timer)
  }, [api, job])
  function patchQuestion(index: number, patch: Partial<Question>) { if (draft) setDraft({ ...draft, questions: draft.questions.map((q, i) => i === index ? { ...q, ...patch } : q) }) }
  function typeChange(index: number, type: QuestionType) {
    const text = ['SHORT_ANSWER', 'OPEN_ANSWER'].includes(type)
    patchQuestion(index, { type, options: text ? [] : type === 'TRUE_FALSE' ? [{ text: 'Вярно', correct: true }, { text: 'Невярно', correct: false }] : [{ text: '', correct: true }, { text: '', correct: false }] })
  }
  async function save(publish = false) {
    if (!draft) return
    await action.run(async () => {
      const saved = await api.call<Assessment>(current ? `/tests/${current.id}` : '/tests', current ? 'PUT' : 'POST', draft)
      setCurrent(saved)
      if (publish) { await api.post(`/tests/${saved.id}/publish`); setCurrent({ ...saved, status: 'published' }) }
      await list.reload()
    }, publish ? 'Публикувана е нова неизменяема версия.' : 'Черновата е запазена.')
  }
  return <section className="ws-section">
    <SectionHead title={draft ? draft.title : 'Библиотека с тестове'}>
      {draft ? <><button title="Към библиотеката" className="icon-button" onClick={() => { setDraft(null); setCurrent(null) }}><ArrowLeft size={18} /></button><button className="command-button" disabled={action.busy || !editable} onClick={() => void save()}><Save size={17} /> Запази</button><button className="primary command-button" disabled={action.busy || !editable} onClick={() => void save(true)}><Send size={17} /> Публикувай версия</button></> : <button className="primary command-button" onClick={() => { setCurrent(null); setDraft(blank()) }}><Plus size={17} /> Нов тест</button>}
    </SectionHead>
    <Feedback error={action.error || list.error} message={action.message} busy={action.busy || list.loading} />
    {!draft ? <>
      <div className="ws-ai-band"><h3><Sparkles size={18} /> AI чернова</h3><div className="ws-form-grid"><label>Тема<input value={topic} maxLength={500} onChange={e => setTopic(e.target.value)} /></label><label>Въпроси<input type="number" min={1} max={20} value={count} onChange={e => setCount(Number(e.target.value))} /></label><label>Трудност<select value={difficulty} onChange={e => setDifficulty(e.target.value)}><option value="EASY">Лесни</option><option value="MEDIUM">Средни</option><option value="HARD">Трудни</option><option value="VERY_HARD">Много трудни</option><option value="MIXED">По разпределение</option></select></label></div><div className="ws-form-grid"><label>Дисциплина<input value={aiSubject} maxLength={190} onChange={e => setAiSubject(e.target.value)} /></label><label>Клас / ниво<input value={aiLevel} maxLength={190} onChange={e => setAiLevel(e.target.value)} /></label><label>Език<select value={aiLanguage} onChange={e => setAiLanguage(e.target.value)}><option value="bg">Български</option><option value="en">Английски</option></select></label></div><div className="ws-actions">{types.map(([key, title]) => <label className="ws-check" key={key}><input type="checkbox" checked={aiTypes.includes(key)} onChange={e => setAiTypes(e.target.checked ? [...aiTypes, key] : aiTypes.filter(t => t !== key))} />{title}</label>)}</div>{difficulty === 'MIXED' && <div className="ws-form-grid">{Object.entries({ EASY: 'Лесни', MEDIUM: 'Средни', HARD: 'Трудни', VERY_HARD: 'Много трудни' }).map(([key, title]) => <label key={key}>{title}<input type="number" min={0} max={20} value={distribution[key]} onChange={e => setDistribution({ ...distribution, [key]: Number(e.target.value) })} /></label>)}</div>}<label>Учебен текст<textarea value={source} maxLength={20000} onChange={e => setSource(e.target.value)} /></label><div className="ws-actions"><button disabled={action.busy || !!job && ['queued', 'running'].includes(job.status)} onClick={() => void action.run(async () => { setReplacements([]); setJob(await api.post<AiJob>('/ai/test-generations', { requestKey: crypto.randomUUID(), topic, subject: aiSubject, level: aiLevel, language: aiLanguage, questionCount: count, difficulty, sourceText: source, questionTypes: aiTypes, difficultyCounts: difficulty === 'MIXED' ? distribution : { [difficulty]: count } })) })}><Sparkles size={16} /> Генерирай</button>{job && <span role="status">{label(job.status)}</span>}{job?.status === 'completed' && <button onClick={() => { reviewJob() }}><Check size={16} /> Прегледай черновата</button>}{job?.status === 'failed' && <><span className="error">{job.error_message}</span><button onClick={() => void action.run(async () => setJob(await api.post<AiJob>(`/ai/test-generations/${job.id}/retry`)))}>Повтори</button></>}</div></div>
      <div className="ws-table-wrap"><table className="ws-table"><thead><tr><th>Тест</th><th>Статус</th><th>Достъп</th><th>Променен</th><th>Действия</th></tr></thead><tbody>{list.data.map(test => <tr key={test.id}><td><button className="ws-text-button" onClick={() => void action.run(async () => { const row = await api.get<Assessment>(`/tests/${test.id}`); setCurrent(row); setDraft(JSON.parse(row.definition_json)) })}>{test.title}</button></td><td>{label(test.status)}</td><td>{test.shared ? 'Споделен' : 'Личен'}</td><td>{date(test.updated_at)}</td><td><div className="ws-actions"><button className="icon-button" title="Дублирай" onClick={() => void action.run(async () => { await api.post(`/tests/${test.id}/duplicate`); await list.reload() })}><Copy size={17} /></button>{test.owner_id === userId && <><button className="icon-button" title={test.shared ? 'Направи личен' : 'Сподели в организацията'} onClick={() => void action.run(async () => { await api.put(`/tests/${test.id}/sharing`, { shared: !test.shared }); await list.reload() })}><Library size={17} /></button><button className="icon-button danger" title="Изтрий / архивирай" onClick={() => setPendingDelete(test)}><Trash2 size={17} /></button></>}</div></td></tr>)}</tbody></table></div>{!list.data.length && !list.loading && <Empty />}
    </> : <fieldset className="ws-editor" disabled={action.busy || !editable}>
      <div className="ws-inline-form"><label>Банка с въпроси<select value={bankItem} onChange={e => setBankItem(e.target.value)}><option value="">Избери въпрос</option>{bank.data.map(q => <option key={q.id} value={q.id}>{q.subject} · {(JSON.parse(q.definition_json) as Question).text}</option>)}</select></label><button disabled={!bankItem} onClick={() => { const item = bank.data.find(q => q.id === Number(bankItem)); if (item) setDraft({ ...draft, questions: [...draft.questions, JSON.parse(item.definition_json) as Question] }) }}><Plus size={16} /> Добави от банката</button><button disabled={!selectedQuestions.length || !!job && ['queued', 'running'].includes(job.status)} onClick={() => void action.run(async () => { setReplacements(selectedQuestions); const chosen = draft.questions.filter((_, i) => selectedQuestions.includes(i)); const counts: Record<string, number> = {}; chosen.forEach(q => { counts[q.difficulty] = (counts[q.difficulty] ?? 0) + 1 }); setJob(await api.post<AiJob>('/ai/test-generations', { requestKey: crypto.randomUUID(), topic: draft.title, subject: draft.subject, level: draft.level, language: draft.language, questionCount: chosen.length, difficulty: 'MIXED', sourceText: chosen.map(q => q.text).join('\\n'), questionTypes: [...new Set(chosen.map(q => q.type))], difficultyCounts: counts })) })}><Sparkles size={16} /> Генерирай избраните отново</button></div>
      {job && <div className="ws-actions"><span role="status">{label(job.status)}</span>{job.status === 'completed' && <button onClick={reviewJob}><Check size={16} /> Прегледай новите въпроси</button>}{job.status === 'failed' && <span className="error">{job.error_message}</span>}</div>}
      <div className="ws-form-grid"><label>Заглавие<input value={draft.title} maxLength={190} onChange={e => setDraft({ ...draft, title: e.target.value })} /></label><label>Дисциплина<input value={draft.subject} onChange={e => setDraft({ ...draft, subject: e.target.value })} /></label><label>Клас / ниво<input value={draft.level} onChange={e => setDraft({ ...draft, level: e.target.value })} /></label><label>Език<select value={draft.language} onChange={e => setDraft({ ...draft, language: e.target.value })}><option value="bg">Български</option><option value="Bulgarian">Български</option><option value="en">Английски</option></select></label></div>
      <label>Описание<textarea value={draft.description ?? ''} onChange={e => setDraft({ ...draft, description: e.target.value })} /></label><label>Инструкции за изпита<textarea value={draft.instructions ?? ''} onChange={e => setDraft({ ...draft, instructions: e.target.value })} /></label>
      <div className="ws-form-grid"><label>Скала<select value={draft.gradingScale} onChange={e => setDraft({ ...draft, gradingScale: e.target.value })}><option value="bulgarian">Българска (2–6)</option><option value="percentage">Процент</option><option value="pass_fail">Успешен / неуспешен</option></select></label><label>Праг за успех (%)<input type="number" min={0} max={100} value={draft.passThreshold} onChange={e => setDraft({ ...draft, passThreshold: Number(e.target.value) })} /></label><p className="ws-summary">{draft.questions.length} въпроса · {draft.questions.reduce((sum, q) => sum + q.points, 0)} точки · {draft.questions.reduce((sum, q) => sum + q.timeSeconds, 0)} секунди</p></div>
      {draft.questions.map((q, index) => <article className="ws-question" key={index}><div className="ws-question-head"><label className="ws-check"><input type="checkbox" checked={selectedQuestions.includes(index)} onChange={e => setSelectedQuestions(e.target.checked ? [...selectedQuestions, index].sort((a, b) => a - b) : selectedQuestions.filter(i => i !== index))} />Въпрос {index + 1}</label><button className="icon-button" title="Запази въпроса в банката" onClick={() => void action.run(async () => { await api.post('/question-bank', { subject: draft.subject, shared: false, question: q }); await bank.reload() }, 'Въпросът е запазен в банката.')}><Library size={17} /></button><button className="icon-button" title="Сподели въпроса в организационната банка" onClick={() => void action.run(async () => { await api.post('/question-bank', { subject: draft.subject, shared: true, question: q }); await bank.reload() }, 'Въпросът е споделен.')}><Copy size={17} /></button><select aria-label={`Тип на въпрос ${index + 1}`} value={q.type} onChange={e => typeChange(index, e.target.value as QuestionType)}>{types.map(([type, text]) => <option key={type} value={type}>{text}</option>)}</select><button className="icon-button danger" title="Изтрий въпрос" onClick={() => setDraft({ ...draft, questions: draft.questions.filter((_, i) => i !== index) })}><Trash2 size={17} /></button></div><label>Текст<textarea value={q.text} onChange={e => patchQuestion(index, { text: e.target.value })} /></label><div className="ws-form-grid"><label>Трудност<select value={q.difficulty} onChange={e => patchQuestion(index, { difficulty: e.target.value, timeSeconds: ({ EASY: 30, MEDIUM: 60, HARD: 120, VERY_HARD: 180 })[e.target.value as 'EASY'] })}><option value="EASY">Лесен</option><option value="MEDIUM">Среден</option><option value="HARD">Труден</option><option value="VERY_HARD">Много труден</option></select></label><label>Точки<input type="number" min={0.0001} step="0.1" value={q.points} onChange={e => patchQuestion(index, { points: Number(e.target.value) })} /></label><label>Време (s)<input type="number" min={10} max={3600} value={q.timeSeconds} onChange={e => patchQuestion(index, { timeSeconds: Number(e.target.value) })} /></label></div>
        {q.options.map((option, i) => <div className="ws-option-editor" key={i}><input aria-label={`Верен отговор ${i + 1}`} type={q.type === 'MULTIPLE_CHOICE' ? 'checkbox' : 'radio'} name={`correct-${index}`} checked={option.correct} onChange={e => patchQuestion(index, { options: q.options.map((o, j) => j === i ? { ...o, correct: e.target.checked } : q.type === 'MULTIPLE_CHOICE' ? o : { ...o, correct: false }) })} /><input aria-label={`Опция ${i + 1}`} value={option.text} onChange={e => patchQuestion(index, { options: q.options.map((o, j) => j === i ? { ...o, text: e.target.value } : o) })} /><button className="icon-button" title="Премахни опция" onClick={() => patchQuestion(index, { options: q.options.filter((_, j) => j !== i) })}><X size={16} /></button></div>)}
        {['SINGLE_CHOICE', 'MULTIPLE_CHOICE'].includes(q.type) && <button className="command-button" onClick={() => patchQuestion(index, { options: [...q.options, { text: '', correct: false }] })}><Plus size={16} /> Опция</button>}
        {q.type === 'SHORT_ANSWER' && <><label>Допустими отговори (по един на ред)<textarea value={q.acceptedAnswers.join('\n')} onChange={e => patchQuestion(index, { acceptedAnswers: e.target.value ? e.target.value.split('\n') : [] })} /></label><div className="ws-actions"><label className="ws-check"><input type="checkbox" checked={q.caseInsensitive} onChange={e => patchQuestion(index, { caseInsensitive: e.target.checked })} /> Без разлика малки / главни</label><label className="ws-check"><input type="checkbox" checked={q.collapseWhitespace} onChange={e => patchQuestion(index, { collapseWhitespace: e.target.checked })} /> Нормализирай интервали</label></div></>}
        {['SHORT_ANSWER', 'OPEN_ANSWER'].includes(q.type) && <label>Критерии за ръчна проверка<textarea value={q.criteria} onChange={e => patchQuestion(index, { criteria: e.target.value })} /></label>}<div className="ws-actions"><label className="ws-file">Изображение<input type="file" accept="image/png,image/jpeg" onChange={e => { const file = e.target.files?.[0]; if (file) void action.run(async () => { const value = await api.post<{ id: number }>('/files', { purpose: 'question', base64: await imageBase64(file) }); patchQuestion(index, { imageId: value.id }) }) }} /></label>{q.imageId && <button className="icon-button" title="Премахни изображението от въпроса" onClick={() => patchQuestion(index, { imageId: null })}><X size={16} /></button>}</div><WorkspaceImage api={api} id={q.imageId} /><label>Обяснение след разрешен преглед<textarea value={q.explanation ?? ''} onChange={e => patchQuestion(index, { explanation: e.target.value })} /></label>
      </article>)}<button className="command-button" onClick={() => setDraft({ ...draft, questions: [...draft.questions, question()] })}><Plus size={17} /> Добави въпрос</button>
    </fieldset>}
    {pendingDelete && <div className="dialog-backdrop"><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="remove-title"><h2 id="remove-title">Премахване на тест</h2><p>{pendingDelete.title}</p><p>Публикуваните версии и старите опити се запазват в архива.</p><div className="ws-actions"><button onClick={() => setPendingDelete(null)}>Отказ</button><button className="danger" disabled={action.busy} onClick={() => void action.run(async () => { await api.remove(`/tests/${pendingDelete.id}`); setPendingDelete(null); await list.reload() })}><Trash2 size={16} /> Потвърди</button></div></section></div>}
  </section>
}
