import { useState } from 'react'
import { Plus, UserPlus, Trash2, FileUp, ArrowLeft, Save } from 'lucide-react'
import type { WorkspaceApi } from './api'
import { useAction, useRemote } from './api'
import type { Group, Member } from './types'
import { roles, date, label } from './types'
import { Empty, Feedback, SectionHead } from './ui'

export function GroupsPanel({ api, teacher }: { api: WorkspaceApi; teacher: boolean }) {
  const groups = useRemote<Group[]>(api, '/groups', [])
  const action = useAction()
  const [description, setDescription] = useState(''), [year, setYear] = useState('2026/2027'), [classLabel, setClassLabel] = useState('')
  const [name, setName] = useState('')
  const [subject, setSubject] = useState('')
  const [selected, setSelected] = useState<Group | null>(null)
  if (selected && !teacher) return <GroupSummary api={api} group={selected} back={() => setSelected(null)} />
  if (selected && teacher) return <GroupMembers api={api} group={selected} back={() => setSelected(null)} />
  return <section className="ws-section"><SectionHead title="Групи" /><Feedback error={groups.error || action.error} message={action.message} busy={groups.loading || action.busy} />
    {teacher && <form className="ws-inline-form" onSubmit={e => { e.preventDefault(); void action.run(async () => { await api.post('/groups', { name, subject, description, schoolYear: year, classLabel }); setName(''); await groups.reload() }, 'Групата е създадена.') }}><label>Име<input required maxLength={190} value={name} onChange={e => setName(e.target.value)} /></label><label>Дисциплина<input value={subject} onChange={e => setSubject(e.target.value)} /></label><label>Учебна година<input maxLength={40} value={year} onChange={e => setYear(e.target.value)} /></label><label>Клас / курс<input maxLength={80} value={classLabel} onChange={e => setClassLabel(e.target.value)} /></label><label>Описание<input maxLength={4000} value={description} onChange={e => setDescription(e.target.value)} /></label><button className="primary command-button" disabled={action.busy}><Plus size={17} /> Създай група</button></form>}
    <div className="ws-table-wrap"><table className="ws-table"><thead><tr><th>Група</th><th>Дисциплина</th><th>Учебна година</th><th>Клас / курс</th></tr></thead><tbody>{groups.data.map(group => <tr key={group.id}><td>{<button className="ws-text-button" onClick={() => setSelected(group)}>{group.name}</button>}</td><td>{group.subject}</td><td>{group.school_year}</td><td>{group.class_label}</td></tr>)}</tbody></table></div>{!groups.data.length && !groups.loading && <Empty />}
  </section>
}
function GroupMembers({ api, group, back }: { api: WorkspaceApi; group: Group; back: () => void }) {
  const members = useRemote<(Member & { active: boolean })[]>(api, `/groups/${group.id}/members`, [])
  const directory = useRemote<Member[]>(api, '/members', [])
  const action = useAction()
  const teachers = useRemote<{ user_id: number; name: string }[]>(api, `/groups/${group.id}/teachers`, [])
  const [coTeacher, setCoTeacher] = useState(''), [editing, setEditing] = useState(group)
  const [user, setUser] = useState('')
  const [email, setEmail] = useState('')
  const [invite, setInvite] = useState('')
  const [csv, setCsv] = useState('email\n')
  const [preview, setPreview] = useState<{ row: number; email: string; status: string; user_id?: number }[]>([])
  const [importReport, setImportReport] = useState<string[]>([])
  return <section className="ws-section"><SectionHead title={group.name}><button className="icon-button" title="Към групите" onClick={back}><ArrowLeft size={18} /></button></SectionHead><Feedback error={members.error || directory.error || action.error} message={action.message} busy={action.busy} />
    <form className="ws-inline-form" onSubmit={e => { e.preventDefault(); void action.run(async () => { await api.post(`/groups/${group.id}/members`, { userId: Number(user) }); await members.reload() }, 'Обучаемият е добавен.') }}><label>Обучаем<select required value={user} onChange={e => setUser(e.target.value)}><option value="">Избери член</option>{directory.data.filter(m => m.status === 'active' && roles(m).includes('STUDENT')).map(m => <option value={m.user_id} key={m.user_id}>{m.name} · {m.email}</option>)}</select></label><button disabled={!user || action.busy}><UserPlus size={17} /> Добави</button></form>
    <form className="ws-inline-form" onSubmit={e => { e.preventDefault(); void action.run(async () => { const value = await api.post<{ token: string }>('/invitations', { email, roles: ['STUDENT'], groupId: group.id }); setInvite(value.token) }) }}><label>Покана по имейл<input type="email" required value={email} onChange={e => setEmail(e.target.value)} /></label><button disabled={action.busy}><UserPlus size={17} /> Създай покана</button></form>{invite && <label>Еднократен токен за покана<input readOnly value={invite} /></label>}
    <div className="ws-table-wrap"><table className="ws-table"><thead><tr><th>Име</th><th>Имейл</th><th>Статус</th><th>Действие</th></tr></thead><tbody>{members.data.map(m => <tr key={m.user_id}><td>{m.name}</td><td>{m.email}</td><td>{m.active ? 'В групата' : 'Премахнат'}</td><td>{m.active && <button className="icon-button danger" title="Премахни от групата" onClick={() => void action.run(async () => { await api.remove(`/groups/${group.id}/members/${m.user_id}`); await members.reload() })}><Trash2 size={17} /></button>}</td></tr>)}</tbody></table></div>
    <h3>Учители на групата</h3><div className="ws-actions">{teachers.data.map(t => <span key={t.user_id}>{t.name}<button className="icon-button danger" title="Премахни учителя" onClick={() => void action.run(async () => { await api.remove(`/groups/${group.id}/teachers/${t.user_id}`); await teachers.reload() })}><Trash2 size={15} /></button></span>)}</div><form className="ws-inline-form" onSubmit={e => { e.preventDefault(); void action.run(async () => { await api.post(`/groups/${group.id}/teachers`, { userId: Number(coTeacher) }); await teachers.reload() }) }}><label>Друг учител<select required value={coTeacher} onChange={e => setCoTeacher(e.target.value)}><option value="">Избери</option>{directory.data.filter(m => m.status === 'active' && roles(m).includes('TEACHER')).map(m => <option key={m.user_id} value={m.user_id}>{m.name}</option>)}</select></label><button disabled={action.busy || !coTeacher}><UserPlus size={17} /> Добави учител</button></form>
    <h3>Данни за групата</h3><form onSubmit={e => { e.preventDefault(); void action.run(() => api.put(`/groups/${group.id}`, { profile: { name: editing.name, subject: editing.subject, description: editing.description, schoolYear: editing.school_year, classLabel: editing.class_label }, status: editing.status }), 'Групата е обновена.') }}><div className="ws-form-grid">{([['name', 'Име'], ['subject', 'Дисциплина'], ['school_year', 'Учебна година'], ['class_label', 'Клас / курс'], ['description', 'Описание']] as const).map(([key, title]) => <label key={key}>{title}<input value={editing[key]} onChange={e => setEditing({ ...editing, [key]: e.target.value })} /></label>)}<label>Статус<select value={editing.status} onChange={e => setEditing({ ...editing, status: e.target.value })}><option value="active">Активна</option><option value="archived">Архивирана</option></select></label></div><button disabled={action.busy}><Save size={17} /> Запази</button></form>
    <GroupSummary api={api} group={editing} embedded />
    <h3>CSV импорт</h3><label>CSV с колона email<textarea value={csv} onChange={e => setCsv(e.target.value)} /></label><div className="ws-actions"><label className="ws-file"><FileUp size={17} /> Файл<input type="file" accept=".csv,text/csv" onChange={e => { const file = e.target.files?.[0]; if (file && file.size <= 200000) void file.text().then(setCsv) }} /></label><button onClick={() => void action.run(async () => setPreview(await api.post(`/groups/${group.id}/csv/preview`, { csv })))}>Преглед</button>{preview.length > 0 && <button disabled={action.busy} onClick={() => void action.run(async () => { const report: string[] = []; for (const row of preview) { if (!['member', 'invitation'].includes(row.status)) continue; try { if (row.user_id) await api.post(`/groups/${group.id}/members`, { userId: row.user_id }); else { const result = await api.post<{ token: string }>('/invitations', { email: row.email, roles: ['STUDENT'], groupId: group.id }); report.push(`${row.email}: ${result.token}`) } } catch (cause) { report.push(`${row.email}: ${cause instanceof Error ? cause.message : 'Грешка'}`) } } setImportReport(report); setPreview([]); await members.reload() }, 'Импортът е обработен.')}>Потвърди валидните редове</button>}</div>
    {preview.length > 0 && <table className="ws-table"><thead><tr><th>Ред</th><th>Имейл</th><th>Статус</th></tr></thead><tbody>{preview.map(row => <tr key={row.row}><td>{row.row}</td><td>{row.email}</td><td>{{ invalid: 'Невалиден', duplicate: 'Дублиран', member: 'Съществуващ член', invitation: 'Покана' }[row.status]}</td></tr>)}</tbody></table>}{importReport.length > 0 && <label>Отчет / токени за покани<textarea readOnly value={importReport.join('\n')} /></label>}
  </section>
}

type GroupSummaryData = { group: Group; teachers: { name: string }[]; conversationId: number | null; assignments: { assignment_id: number; student_id: number; student_name: string; title: string; ends_at: string; attempts: { id: number; attempt_number: number; status: string; grade: string | null; outcome: string | null }[] }[] }
function GroupSummary({ api, group, embedded = false, back }: { api: WorkspaceApi; group: Group; embedded?: boolean; back?: () => void }) {
  const data = useRemote<GroupSummaryData | null>(api, `/groups/${group.id}/summary`, null)
  return <section className={embedded ? 'ws-group-report' : 'ws-section'}><SectionHead title={embedded ? 'Възлагания и резултати' : group.name}>{back && <button className="icon-button" title="Към групите" onClick={back}><ArrowLeft size={17} /></button>}{data.data?.conversationId && <button onClick={() => window.dispatchEvent(new CustomEvent('examai:open-chat', { detail: data.data?.conversationId }))}>Групов чат</button>}</SectionHead><p className="ws-muted">Обобщена оценка: последният публикуван, неанулиран опит по пореден номер.</p><Feedback error={data.error} busy={data.loading} /><p>{group.subject} · {group.school_year} · {group.class_label}</p><p>{group.description}</p><p>{data.data?.teachers.map(t => t.name).join(' · ')}</p><div className="ws-table-wrap"><table className="ws-table"><thead><tr><th>Тест</th><th>Обучаем</th><th>Срок</th><th>Обобщена оценка</th><th>Всички опити</th></tr></thead><tbody>{data.data?.assignments.map(a => <tr key={`${a.assignment_id}-${a.student_id}`}><td>{a.title}</td><td>{a.student_name}</td><td>{date(a.ends_at)}</td><td>{a.attempts.find(x => x.status === 'finalized')?.grade ?? '-'}</td><td>{a.attempts.length ? a.attempts.map(x => <div key={x.id}>#{x.attempt_number} · {label(x.status)}{x.grade ? ` · ${x.grade} · ${label(x.outcome ?? '')}` : ''}</div>) : 'Не е започнал'}</td></tr>)}</tbody></table></div></section>
}
