import { useState } from 'react'
import { Save, Plus, Shield, Ban } from 'lucide-react'
import type { AuthResponse } from '../types/models'
import { AdminPanel } from '../components/AdminPanel'
import type { WorkspaceApi } from './api'
import { useAction, useRemote } from './api'
import { date, label } from './types'
import { Feedback, SectionHead } from './ui'
type Org = { id: number; name: string; status: string; contact_email: string; plan_name: string; subscription_status: string; paid_through: string }
type Plan = { id?: number; name: string; monthly_eur: number; yearly_eur: number; teacher_limit: number; student_limit: number; ai_limit: number; storage_bytes: number; demonstration: boolean; month_price_id: string | null; year_price_id: string | null }
export function PlatformPanel({ api, auth, refresh }: { api: WorkspaceApi; auth: AuthResponse; refresh: () => Promise<void> }) {
  const organizations = useRemote<Org[]>(api, '/platform/organizations', []), plans = useRemote<Plan[]>(api, '/platform/plans', [])
  const action = useAction()
  const [editing, setEditing] = useState<Plan | null>(null), [support, setSupport] = useState<Record<string, unknown>[] | null>(null)
  function field<K extends keyof Plan>(key: K, value: Plan[K]) { if (editing) setEditing({ ...editing, [key]: value }) }
  return <><section className="ws-section"><SectionHead title="Организации и планове" /><Feedback error={action.error || organizations.error || plans.error} message={action.message} busy={action.busy} /><div className="ws-table-wrap"><table className="ws-table"><thead><tr><th>Организация</th><th>Контакт</th><th>План</th><th>Абонамент</th><th>Достъп до</th><th>Действия</th></tr></thead><tbody>{organizations.data.map(o => <tr key={o.id}><td>{o.name}</td><td>{o.contact_email}</td><td>{o.plan_name}</td><td>{label(o.subscription_status)}</td><td>{date(o.paid_through)}</td><td><div className="ws-actions"><button className="icon-button" title="Одобрена поддръжка" onClick={() => void action.run(async () => setSupport(await api.get(`/platform/support/${o.id}`)))}><Shield size={17} /></button><button className="icon-button danger" title={o.status === 'active' ? 'Деактивирай организацията' : 'Активирай организацията'} onClick={() => { const reason = window.prompt('Причина за промяна на статуса'); if (reason) void action.run(async () => { await api.put(`/platform/organizations/${o.id}/status`, { status: o.status === 'active' ? 'inactive' : 'active', reason }); await organizations.reload() }) }}><Ban size={17} /></button></div></td></tr>)}</tbody></table></div>{support && <><h3>Разрешен преглед на опити</h3><div className="ws-table-wrap"><table className="ws-table"><thead><tr><th>Опит</th><th>Тест</th><th>Статус</th><th>Предаден</th></tr></thead><tbody>{support.map(row => <tr key={String(row.id)}><td>{String(row.id)}</td><td>{String(row.title)}</td><td>{label(String(row.status))}</td><td>{date(row.submitted_at as string | null)}</td></tr>)}</tbody></table></div></>}
    <SectionHead title="Планове"><button onClick={() => setEditing({ name: '', monthly_eur: 0, yearly_eur: 0, teacher_limit: 5, student_limit: 100, ai_limit: 50, storage_bytes: 1000000000, demonstration: true, month_price_id: '', year_price_id: '' })}><Plus size={17} /> План</button></SectionHead><div className="ws-table-wrap"><table className="ws-table"><thead><tr><th>План</th><th>Месец / година (EUR)</th><th>Учители / обучаеми</th><th>AI</th><th>Хранилище</th><th>Цени</th></tr></thead><tbody>{plans.data.map(p => <tr key={p.id}><td><button className="ws-text-button" onClick={() => setEditing(p)}>{p.name}</button></td><td>{p.monthly_eur} / {p.yearly_eur}</td><td>{p.teacher_limit} / {p.student_limit}</td><td>{p.ai_limit}</td><td>{(p.storage_bytes / 1000000000).toFixed(1)} GB</td><td>{p.demonstration ? 'Демонстрационни' : 'Търговски'}</td></tr>)}</tbody></table></div>
    {editing && <form onSubmit={e => { e.preventDefault(); void action.run(async () => { await api.call(editing.id ? `/platform/plans/${editing.id}` : '/platform/plans', editing.id ? 'PUT' : 'POST', { name: editing.name, monthlyEur: editing.monthly_eur, yearlyEur: editing.yearly_eur, teacherLimit: editing.teacher_limit, studentLimit: editing.student_limit, aiLimit: editing.ai_limit, storageBytes: editing.storage_bytes, demonstration: editing.demonstration, monthPriceId: editing.month_price_id, yearPriceId: editing.year_price_id }); await plans.reload(); setEditing(null) }) }}><div className="ws-form-grid"><label>Име<input required maxLength={80} value={editing.name} onChange={e => field('name', e.target.value)} /></label>{([['monthly_eur', 'Месечна цена'], ['yearly_eur', 'Годишна цена'], ['teacher_limit', 'Учители'], ['student_limit', 'Обучаеми'], ['ai_limit', 'AI за период'], ['storage_bytes', 'Хранилище (bytes)']] as const).map(([key, title]) => <label key={key}>{title}<input type="number" min={0} step={key.endsWith('eur') ? 0.01 : 1} value={editing[key]} onChange={e => field(key, Number(e.target.value))} /></label>)}<label>Stripe месечен price ID<input value={editing.month_price_id ?? ''} onChange={e => field('month_price_id', e.target.value)} /></label><label>Stripe годишен price ID<input value={editing.year_price_id ?? ''} onChange={e => field('year_price_id', e.target.value)} /></label></div><div className="ws-actions"><label className="ws-check"><input type="checkbox" checked={editing.demonstration} onChange={e => field('demonstration', e.target.checked)} /> Демонстрационни цени</label><button disabled={action.busy}><Save size={17} /> Запази</button><button type="button" onClick={() => setEditing(null)}>Отказ</button></div></form>}
  </section><details className="ws-section"><summary>Потребители и техническо администриране</summary><AdminPanel auth={auth} onProfileRefresh={refresh} /></details></>
}
