import { useState } from 'react'
import { Save, Download, Shield, Trash2 } from 'lucide-react'
import type { WorkspaceApi } from './api'
import { useAction, useRemote } from './api'
import { date } from './types'
import { Feedback, SectionHead } from './ui'
import { WorkspaceImage } from './WorkspaceImage'
import { imageBase64 } from './imageUpload'
type Settings = { logo_id?: number | null; name: string; organization_type: string; contact_email: string; timezone: string; student_label: string; settings_json: string }
type Permission = { key: string; controller: string; method: string; paths: string[]; teacher: boolean; student: boolean; teacherAvailable: boolean; studentAvailable: boolean }
type Grant = { id: number; administrator: string; reason: string; expires_at: string; revoked_at: string | null }
export function SettingsPanel({ api }: { api: WorkspaceApi }) {
  const settings = useRemote<Settings | null>(api, '/settings', null), matrix = useRemote<Permission[]>(api, '/permissions', []), grants = useRemote<Grant[]>(api, '/support-grants', []), admins = useRemote<{ id: number; name: string }[]>(api, '/support-administrators', [])
  const action = useAction()
  const [filter, setFilter] = useState(''), [administrator, setAdministrator] = useState(''), [reason, setReason] = useState(''), [hours, setHours] = useState(1), [editing, setEditing] = useState<Settings | null>(null)
  const value = editing ?? settings.data
  const policy = value ? JSON.parse(value.settings_json) as { studentChat?: boolean; retentionDays?: number; retentionApproved?: boolean; gradingScale?: string; passThreshold?: number } : {}
  function change(patch: Partial<Settings>) { if (value) setEditing({ ...value, ...patch }) }
  function changePolicy(patch: typeof policy) { change({ settings_json: JSON.stringify({ ...policy, ...patch }) }) }
  return <section className="ws-section"><SectionHead title="Настройки на организацията"><button onClick={() => void action.run(async () => { const data = await api.get('/export'); const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `examai-export-${Date.now()}.json`; link.click(); URL.revokeObjectURL(url) })}><Download size={17} /> Експорт</button></SectionHead><Feedback error={action.error || settings.error || matrix.error || grants.error} message={action.message} busy={action.busy} />
    {value && <form onSubmit={e => { e.preventDefault(); void action.run(async () => { await api.put('/settings', { profile: { name: value.name, organizationType: value.organization_type, contactEmail: value.contact_email, timezone: value.timezone, studentLabel: value.student_label }, studentChat: !!policy.studentChat, retentionDays: policy.retentionDays ?? 365, retentionApproved: !!policy.retentionApproved, gradingScale: policy.gradingScale ?? 'bulgarian', passThreshold: policy.passThreshold ?? 50 }); await settings.reload(); window.dispatchEvent(new Event('examai:organizations-refresh')) }, 'Настройките са запазени.') }}><div className="ws-form-grid">{([['name', 'Име'], ['contact_email', 'Контактен имейл'], ['timezone', 'Часова зона']] as const).map(([key, title]) => <label key={key}>{title}<input required maxLength={190} value={value[key]} onChange={e => change({ [key]: e.target.value })} /></label>)}<label>Тип<select value={value.organization_type} onChange={e => change({ organization_type: e.target.value })}><option value="school">Училище</option><option value="university">Университет</option><option value="training">Обучителен център</option></select></label><label>Обучаем<select value={value.student_label} onChange={e => change({ student_label: e.target.value })}><option>Ученик</option><option>Студент</option><option>Курсист</option></select></label><label>Скала<select value={policy.gradingScale ?? 'bulgarian'} onChange={e => changePolicy({ gradingScale: e.target.value })}><option value="bulgarian">Българска (2–6)</option><option value="percentage">Процент</option><option value="pass_fail">Успешен / неуспешен</option></select></label><label>Праг (%)<input type="number" min={0} max={100} value={policy.passThreshold ?? 50} onChange={e => changePolicy({ passThreshold: Number(e.target.value) })} /></label><label>Съхранение (дни)<input type="number" min={30} max={36500} value={policy.retentionDays ?? 365} onChange={e => changePolicy({ retentionDays: Number(e.target.value) })} /></label></div><div className="ws-actions"><label className="ws-check"><input type="checkbox" checked={!!policy.studentChat} onChange={e => changePolicy({ studentChat: e.target.checked })} /> Чат между обучаеми</label><label className="ws-check"><input type="checkbox" checked={!!policy.retentionApproved} onChange={e => changePolicy({ retentionApproved: e.target.checked })} /> Одобрена политика</label><button disabled={action.busy}><Save size={17} /> Запази</button></div></form>}
    <div className="ws-actions"><WorkspaceImage api={api} id={value?.logo_id} logo /><label className="ws-file">Лого<input type="file" accept="image/png,image/jpeg" onChange={e => { const file = e.target.files?.[0]; if (file) void action.run(async () => { await api.post('/files', { purpose: 'logo', base64: await imageBase64(file) }); const next = await settings.reload(); setEditing(next); window.dispatchEvent(new Event('examai:organizations-refresh')) }) }} /></label></div>
    <h3>Контролери и методи</h3><label>Търсене<input value={filter} onChange={e => setFilter(e.target.value)} /></label><div className="ws-table-wrap"><table className="ws-table"><thead><tr><th>Контролер</th><th>Метод / адрес</th><th>Учител</th><th>Обучаем</th></tr></thead><tbody>{matrix.data.filter(p => `${p.key} ${p.paths.join(' ')}`.toLowerCase().includes(filter.toLowerCase())).map(p => <tr key={p.key}><td>{p.controller}</td><td><strong>{p.method}</strong><small>{p.paths.join(', ')}</small></td>{(['teacher', 'student'] as const).map(role => <td key={role}><input type="checkbox" aria-label={`${p.key} ${role}`} checked={p[role]} disabled={action.busy || !p[`${role}Available`]} onChange={e => void action.run(async () => { await api.put('/permissions', { key: p.key, role: role.toUpperCase(), allowed: e.target.checked }); await matrix.reload() })} /></td>)}</tr>)}</tbody></table></div>
    <h3><Shield size={17} /> Временна поддръжка</h3><form className="ws-inline-form" onSubmit={e => { e.preventDefault(); void action.run(async () => { await api.post('/support-grants', { administratorId: Number(administrator), reason, hours }); await grants.reload(); setReason('') }) }}><label>Администратор<select required value={administrator} onChange={e => setAdministrator(e.target.value)}><option value="">Избери</option>{admins.data.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Причина<input required maxLength={1000} value={reason} onChange={e => setReason(e.target.value)} /></label><label>Часове<input type="number" min={1} max={24} value={hours} onChange={e => setHours(Number(e.target.value))} /></label><button disabled={action.busy}><Shield size={17} /> Разреши четене</button></form><div className="ws-table-wrap"><table className="ws-table"><thead><tr><th>Администратор</th><th>Причина</th><th>Валидност</th><th>Действие</th></tr></thead><tbody>{grants.data.map(g => <tr key={g.id}><td>{g.administrator}</td><td>{g.reason}</td><td>{g.revoked_at ? 'Отнет' : date(g.expires_at)}</td><td>{!g.revoked_at && <button className="icon-button danger" title="Отнеми достъпа" onClick={() => void action.run(async () => { await api.remove(`/support-grants/${g.id}`); await grants.reload() })}><Trash2 size={16} /></button>}</td></tr>)}</tbody></table></div>
    <Retention api={api} />
  </section>
}

function Retention({ api }: { api: WorkspaceApi }) {
  const action = useAction()
  const [preview, setPreview] = useState<{ cutoff: string; attempts: number } | null>(null), [password, setPassword] = useState(''), [reason, setReason] = useState('')
  return <><h3>Изчистване по политика</h3><Feedback error={action.error} message={action.message} /><button onClick={() => void action.run(async () => setPreview(await api.get('/retention/preview')))}>Преглед на изтеклите записи</button>{preview && <form className="ws-inline-form" onSubmit={e => { e.preventDefault(); if (window.confirm(`Окончателно изтриване на отговорите и резултатите на ${preview.attempts} стари опита? Предварително създайте резервно копие.`)) void action.run(async () => { await api.post('/retention/run', { requestKey: crypto.randomUUID(), password, reason }); setPreview(null); setPassword('') }, 'Изчистването е приключило.') }}><p>{preview.attempts} опита преди {date(preview.cutoff)}</p><label>Причина<input required maxLength={1000} value={reason} onChange={e => setReason(e.target.value)} /></label><label>Текуща парола<input required type="password" value={password} onChange={e => setPassword(e.target.value)} /></label><button className="danger" disabled={action.busy || !preview.attempts}><Trash2 size={17} /> Изчисти</button></form>}</>
}
