export interface Member { user_id: number; name: string; email: string; roles_json: string; status: string }
export interface Group { id: number; name: string; description: string; subject: string }
export type QuestionType = 'SINGLE_CHOICE' | 'MULTIPLE_CHOICE' | 'TRUE_FALSE' | 'SHORT_ANSWER' | 'OPEN_ANSWER'
export interface Question { imageId?: number | null; type: QuestionType; text: string; difficulty: string; points: number; timeSeconds: number; options: { text: string; correct: boolean }[]; acceptedAnswers: string[]; caseInsensitive: boolean; collapseWhitespace: boolean; criteria: string; explanation: string }
export interface Definition { title: string; description: string; subject: string; level: string; instructions: string; language: string; gradingScale: string; passThreshold: number; questions: Question[] }
export interface Assessment { id: number; title: string; status: string; shared: boolean; owner_id: number; definition_json: string; updated_at: string; question_count: number; total_time_seconds: number }
export interface Version { id: number; version_number: number; title: string; published_at: string }
export interface Assignment { id: number; teacher_id?: number; title: string; starts_at: string; ends_at: string; max_attempts: number; recipients?: number; recipient_groups?: { id: number; name: string }[]; individual_recipients?: { id: number; name: string }[]; canceled?: boolean; fullscreen_exempt?: boolean }
export interface Attempt { id: number; assignment_id: number; attempt_number: number; status: string; student_name?: string; title: string; submitted_at: string | null; ai_status?: string | null; ai_attempts?: number; ai_error?: string | null }
export interface Result { id: number; assignment_id: number; attempt_id: number; title: string; points: number; maximum_points: number; percentage: number; grade: string; outcome: string; attempt_number: number; revision_number: number; author_id?: number; published_at?: string; reason?: string }
export interface Preflight { mobile_validated?: boolean; id: number; title: string; instructions: string; starts_at: string; ends_at: string; question_count: number; total_seconds: number; fullscreen_exempt: boolean; max_attempts: number }
export interface ExamAnswer { optionIds: string[]; text: string }
export interface ExamState { id: number; assignment_id: number; status: string; server_now: string; question_number: number; question_count: number; question: null | { id: number; imageId?: number | null; type: QuestionType; text: string; status: string; maximum_points: number; time_seconds: number; open_instance: string | null; opened_at: string | null; deadline_at: string | null; options: { id: string; text: string }[]; draft: ExamAnswer | null } }
export interface ExamSession { token: string; browserId: string; startKey: string; attemptId?: number }
export interface ReviewQuestion { id: number; status: string; definition_json: string; maximum_points: number; automatic_points: number | null; final_points: number | null; reviewed: boolean; draft_json: string | null; answer_json: string | null; teacher_comment: string | null; override_reason: string | null; opened_at: string | null; deadline_at: string | null; closed_at: string | null }
export interface Review { attempt: Attempt; student: { id: number; name: string; email: string }; questions: ReviewQuestion[]; events: { event_type: string; question_id: number; received_at: string }[]; revisions: Result[] }
export interface AiJob { id: number; status: string; result_json: string | null; error_message: string | null }
export interface Mail { id: number; notification_type: string; recipient_email: string; payload_json: string; status: string; created_at: string }

export const statusLabels: Record<string, string> = { redacted: 'Изтрит по политика', draft: 'Чернова', published: 'Публикуван', archived: 'Архивиран', in_progress: 'В процес', pending_review: 'Чака проверка', finalized: 'Публикуван резултат', voided: 'Анулиран', queued: 'В опашката', running: 'Обработва се', completed: 'Готов', failed: 'Неуспешен', active: 'Активен', inactive: 'Неактивен', trialing: 'Пробен период', expired: 'Изтекъл', past_due: 'Просрочен', canceled: 'Прекратен', passed: 'Успешен', sent: 'Изпратен', timed_out: 'Времето изтече', invalidated: 'Напуснат изпитен екран', unanswered: 'Без отговор', answered: 'Предаден', open: 'Отворен', pending: 'Не е отворен' }
export const label = (status: string) => statusLabels[status] ?? status
export const date = (value: string | null, timezone = 'Europe/Sofia') => value ? new Date(value).toLocaleString('bg-BG', { timeZone: timezone }) : '-'
export const roles = (org: { roles_json: string }) => JSON.parse(org.roles_json) as string[]
