import assert from 'node:assert/strict'
import { mkdir } from 'node:fs/promises'
import { chromium } from 'playwright'

const base = process.env.E2E_API_URL ?? 'http://localhost:8080'
const frontend = process.env.E2E_FRONTEND_URL ?? 'http://localhost:5173'
const stamp = Date.now()
async function request(path, auth, method = 'GET', data) {
  const response = await fetch(`${base}${path}`, { method, headers: { 'Content-Type': 'application/json', ...(auth ? { Authorization: `Bearer ${auth.token}` } : {}) }, ...(data === undefined ? {} : { body: JSON.stringify(data) }) })
  const text = await response.text()
  return { status: response.status, data: text ? JSON.parse(text) : null }
}
async function account(kind, role) {
  const result = await request('/api/auth/register', null, 'POST', { name: `Group ${kind}`, email: `group-${kind}-${stamp}@example.test`, password: 'test-password-123', role })
  assert.equal(result.status, 200)
  return result.data
}
const teacher = await account('teacher', 'TEACHER')
const outsider = await account('outsider', 'TEACHER')
const student = await account('student', 'STUDENT')
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH ?? (process.platform === 'darwin' ? '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' : undefined), headless: true })
const artifacts = new URL('../../.artifacts/', import.meta.url)
await mkdir(artifacts, { recursive: true })
const errors = []
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, colorScheme: 'light' })
  await context.addInitScript(value => localStorage.setItem('quicktest.auth', JSON.stringify(value)), teacher)
  const page = await context.newPage()
  page.on('pageerror', error => errors.push(error.message))
  let createRequests = 0
  page.on('request', request => { if (request.method() === 'POST' && new URL(request.url()).pathname === '/api/v1/groups') createRequests++ })
  await page.goto(frontend)
  await page.getByRole('button', { name: 'Групи', exact: true }).click()
  const original = `Group ${stamp}`, renamed = `Updated ${stamp}`
  await page.getByText('Няма записи.', { exact: true }).waitFor()
  assert.equal(await page.getByRole('textbox').count(), 0)
  const creation = page.getByRole('dialog', { name: 'Създаване на група', exact: true })
  await page.getByRole('button', { name: 'Създай група', exact: true }).click()
  await creation.waitFor()
  assert.equal(await creation.getByRole('textbox').count(), 3)
  assert.equal(await creation.getByLabel('Име', { exact: true }).evaluate(element => element === document.activeElement), true)
  assert.equal(await creation.getByRole('button', { name: 'Създай група', exact: true }).isDisabled(), true)
  assert.equal(await creation.getByLabel('Учебна година', { exact: true }).count(), 0)
  assert.equal(await creation.getByLabel('Клас / курс', { exact: true }).count(), 0)
  await creation.getByLabel('Име', { exact: true }).fill('   ')
  assert.equal(await creation.getByRole('button', { name: 'Създай група', exact: true }).isDisabled(), true)
  await creation.getByLabel('Име', { exact: true }).fill('Do not create')
  for (let i = 0; i < 6; i++) {
    await page.keyboard.press('Tab')
    assert.equal(await creation.evaluate(element => document.activeElement === document.body || element.contains(document.activeElement)), true)
  }
  await page.keyboard.press('Escape')
  await creation.waitFor({ state: 'detached' })
  assert.equal(createRequests, 0)
  assert.equal(await page.getByRole('button', { name: 'Създай група', exact: true }).evaluate(element => element === document.activeElement), true)
  for (const { theme, width, height } of [{ theme: 'light', width: 1440, height: 1000 }, { theme: 'dark', width: 1440, height: 1000 }, { theme: 'dark', width: 390, height: 844 }, { theme: 'light', width: 390, height: 844 }]) {
    await page.setViewportSize({ width, height })
    if (await page.locator('html').getAttribute('data-theme') !== theme) await page.getByRole('button', { name: theme === 'dark' ? 'Тъмна тема' : 'Светла тема', exact: true }).click()
    await page.getByRole('button', { name: 'Създай група', exact: true }).click()
    assert.equal(await creation.getByLabel('Име', { exact: true }).inputValue(), '')
    await creation.getByLabel('Име', { exact: true }).fill(original)
    await creation.getByLabel('Дисциплина', { exact: true }).fill('Java basics')
    await creation.getByRole('textbox', { name: 'Описание', exact: true }).fill('Introductory group')
    assert.equal(await creation.evaluate(element => { const bounds = element.getBoundingClientRect(); return bounds.left >= 0 && bounds.right <= innerWidth && bounds.top >= 0 && bounds.bottom <= innerHeight && element.scrollWidth <= element.clientWidth }), true)
    await page.screenshot({ path: new URL(`group-create-${theme}-${width}.png`, artifacts).pathname })
    await creation.getByRole('button', { name: 'Отказ', exact: true }).click()
    await creation.waitFor({ state: 'detached' })
  }
  assert.equal(createRequests, 0)
  assert.equal((await request('/api/v1/groups', teacher)).data.length, 0)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('button', { name: 'Създай група', exact: true }).click()
  await creation.getByLabel('Име', { exact: true }).fill(`  ${original}  `)
  await creation.getByLabel('Дисциплина', { exact: true }).fill('Java basics')
  await creation.getByRole('textbox', { name: 'Описание', exact: true }).fill('Introductory group')
  await page.route('**/api/v1/groups', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ detail: 'Неуспешно създаване.' }) }), { times: 1 })
  await creation.getByRole('button', { name: 'Създай група', exact: true }).click()
  await creation.getByRole('alert').getByText('Неуспешно създаване.', { exact: true }).waitFor()
  assert.equal(await creation.getByRole('textbox', { name: 'Описание', exact: true }).inputValue(), 'Introductory group')
  assert.equal((await request('/api/v1/groups', teacher)).data.length, 0)
  let releaseCreation
  const holdCreation = new Promise(resolve => { releaseCreation = resolve })
  await page.route('**/api/v1/groups', async route => { await holdCreation; await route.continue() }, { times: 1 })
  const pendingCreation = page.waitForRequest(request => request.method() === 'POST' && new URL(request.url()).pathname === '/api/v1/groups')
  await creation.getByRole('button', { name: 'Създай група', exact: true }).click()
  assert.deepEqual((await pendingCreation).postDataJSON(), { name: original, subject: 'Java basics', description: 'Introductory group', schoolYear: '', classLabel: '' })
  await page.waitForFunction(() => document.querySelector('dialog button[type="submit"]')?.disabled === true)
  assert.equal(await creation.getByRole('button', { name: 'Отказ', exact: true }).isDisabled(), true)
  assert.equal(await creation.getByLabel('Име', { exact: true }).isDisabled(), true)
  await page.keyboard.press('Escape')
  assert.equal(await creation.isVisible(), true)
  await creation.locator('form').evaluate(form => form.requestSubmit())
  releaseCreation()
  await creation.waitFor({ state: 'detached' })
  assert.equal(createRequests, 2)
  await page.getByText('Групата е създадена.', { exact: true }).waitFor()
  await page.getByRole('button', { name: original, exact: true }).waitFor()
  const group = (await request('/api/v1/groups', teacher)).data.find(g => g.name === original)
  assert.equal(group.subject, 'Java basics')
  assert.equal(group.description, 'Introductory group')
  assert.equal(group.school_year, '')
  assert.equal(group.class_label, '')
  assert.equal((await request(`/api/v1/groups/${group.id}`, outsider, 'DELETE')).status, 403)
  assert.equal((await request(`/api/v1/groups/${group.id}`, student, 'DELETE')).status, 403)
  await page.getByRole('button', { name: original, exact: true }).click()
  const participants = page.getByRole('region', { name: 'Участници в групата', exact: true })
  await participants.getByText('Няма участници в групата.', { exact: true }).waitFor()
  assert.deepEqual(await participants.getByRole('columnheader').allTextContents(), ['Име', 'Имейл', 'Действие'])
  assert.equal(await participants.getByRole('heading', { name: 'Данни за групата' }).count(), 0)
  assert.equal(await participants.getByRole('heading', { name: 'Учител на групата' }).count(), 0)
  assert.equal(await participants.getByRole('heading', { name: 'Възлагания и резултати' }).count(), 0)
  assert.equal(await participants.getByRole('heading', { name: 'CSV импорт' }).count(), 0)
  assert.equal(await participants.getByLabel('Име', { exact: true }).count(), 0)
  assert.equal(await participants.getByRole('button', { name: 'Запази', exact: true }).count(), 0)
  const picker = page.getByRole('combobox', { name: 'Ученик', exact: true })
  await picker.fill(student.user.email)
  const options = page.getByRole('listbox', { name: 'Регистрирани ученици' })
  await options.getByRole('option').filter({ hasText: student.user.email }).waitFor()
  await page.keyboard.press('Enter')
  await page.getByRole('button', { name: 'Добави', exact: true }).click()
  await page.getByRole('cell', { name: student.user.email, exact: true }).waitFor()
  await picker.fill(student.user.email)
  await options.getByText('Няма намерени ученици.', { exact: true }).waitFor()
  await picker.fill(outsider.user.email)
  await options.getByText('Няма намерени ученици.', { exact: true }).waitFor()
  assert.equal((await request(`/api/v1/groups/${group.id}/teachers`, teacher, 'POST', { userId: outsider.user.id })).status, 409)
  assert.equal((await request(`/api/v1/groups/${group.id}/teachers/${teacher.user.id}`, teacher, 'DELETE')).status, 409)
  assert.notEqual((await request(`/api/v1/groups/${group.id}/members`, teacher, 'POST', { userId: outsider.user.id })).status, 200)
  assert.equal((await request(`/api/v1/groups/${group.id}/teachers`, teacher)).data.length, 1)
  const removeMember = participants.getByRole('button', { name: 'Премахни от групата', exact: true })
  const removal = page.getByRole('dialog', { name: 'Премахване на ученик от група', exact: true })
  let removalRequests = 0
  page.on('request', request => { if (request.method() === 'DELETE' && new URL(request.url()).pathname === `/api/v1/groups/${group.id}/members/${student.user.id}`) removalRequests++ })
  await removeMember.click()
  await removal.waitFor()
  assert.equal(removalRequests, 0)
  assert.equal(await removal.getByRole('button', { name: 'Отказ', exact: true }).evaluate(element => element === document.activeElement), true)
  await removal.getByRole('button', { name: 'Отказ', exact: true }).click()
  assert.equal(await removeMember.evaluate(element => element === document.activeElement), true)
  await removeMember.click()
  await page.keyboard.press('Escape')
  await removal.waitFor({ state: 'detached' })
  assert.equal(removalRequests, 0)
  for (const { theme, width, height } of [{ theme: 'light', width: 1440, height: 1000 }, { theme: 'dark', width: 390, height: 844 }]) {
    await page.setViewportSize({ width, height })
    if (await page.locator('html').getAttribute('data-theme') !== theme) await page.getByRole('button', { name: theme === 'dark' ? 'Тъмна тема' : 'Светла тема', exact: true }).click()
    await removeMember.click()
    assert.equal(await removal.evaluate(element => { const bounds = element.getBoundingClientRect(); return bounds.left >= 0 && bounds.right <= innerWidth && bounds.top >= 0 && bounds.bottom <= innerHeight && element.scrollWidth <= element.clientWidth }), true)
    await page.screenshot({ path: new URL(`group-member-remove-${theme}-${width}.png`, artifacts).pathname })
    await removal.getByRole('button', { name: 'Отказ', exact: true }).click()
  }
  await page.getByRole('button', { name: 'Светла тема', exact: true }).click()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await removeMember.click()
  await page.route(`**/api/v1/groups/${group.id}/members/${student.user.id}`, route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ detail: 'Неуспешно премахване.' }) }), { times: 1 })
  await removal.getByRole('button', { name: 'Премахни', exact: true }).click()
  await removal.getByRole('alert').getByText('Неуспешно премахване.', { exact: true }).waitFor()
  assert.equal(removalRequests, 1)
  assert.equal((await request(`/api/v1/groups/${group.id}/members`, teacher)).data.some(m => m.user_id === student.user.id && m.active), true)
  let releaseRemoval
  const holdRemoval = new Promise(resolve => { releaseRemoval = resolve })
  await page.route(`**/api/v1/groups/${group.id}/members/${student.user.id}`, async route => { await holdRemoval; await route.continue() }, { times: 1 })
  const pendingRemoval = page.waitForRequest(request => request.method() === 'DELETE' && new URL(request.url()).pathname === `/api/v1/groups/${group.id}/members/${student.user.id}`)
  await removal.getByRole('button', { name: 'Премахни', exact: true }).click()
  await pendingRemoval
  assert.equal(await removal.getByRole('button', { name: 'Отказ', exact: true }).isDisabled(), true)
  assert.equal(await removal.getByRole('button', { name: 'Изчакване...', exact: true }).isDisabled(), true)
  await page.keyboard.press('Escape')
  assert.equal(await removal.isVisible(), true)
  releaseRemoval()
  await removal.waitFor({ state: 'detached' })
  assert.equal(removalRequests, 2)
  await participants.getByText('Ученикът е премахнат от групата.', { exact: true }).waitFor()
  assert.equal(await participants.getByRole('cell', { name: student.user.email, exact: true }).count(), 0)
  await participants.getByText('Няма участници в групата.', { exact: true }).waitFor()
  await picker.fill(student.user.email)
  await options.getByRole('option').filter({ hasText: student.user.email }).click()
  await participants.getByRole('button', { name: 'Добави', exact: true }).click()
  await participants.getByRole('cell', { name: student.user.email, exact: true }).waitFor()
  await picker.fill('not-found@example.test')
  await options.getByText('Няма намерени ученици.', { exact: true }).waitFor()
  await picker.fill('Group student')
  await page.screenshot({ path: new URL('group-search-desktop.png', artifacts).pathname })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: new URL('group-search-mobile.png', artifacts).pathname })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, JSON.stringify(await page.evaluate(() => [...document.querySelectorAll('body *')].filter(e => e.getBoundingClientRect().right > innerWidth).map(e => [e.tagName, e.className, e.getBoundingClientRect().width]).slice(0, 15))))
  await page.keyboard.press('Escape')
  const table = participants.getByRole('table', { name: 'Участници в групата', exact: true })
  assert.equal(await table.evaluate(element => element.getBoundingClientRect().right <= innerWidth), true)
  assert.equal(await participants.getByRole('button', { name: 'Премахни от групата', exact: true }).evaluate(element => element.getBoundingClientRect().right <= innerWidth), true)
  await page.screenshot({ path: new URL('group-members-mobile.png', artifacts).pathname })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: new URL('group-members-desktop.png', artifacts).pathname })
  await page.getByRole('button', { name: 'Към групите', exact: true }).click()
  const row = () => page.getByRole('row').filter({ has: page.getByRole('button', { name: original, exact: true }) })
  await row().getByRole('button', { name: 'Редактирай групата', exact: true }).click()
  const editor = page.getByRole('region', { name: 'Редактиране на група', exact: true })
  await editor.waitFor()
  assert.equal(await page.getByRole('dialog').count(), 0)
  assert.equal(await editor.getByRole('combobox', { name: 'Ученик', exact: true }).count(), 0)
  await page.waitForFunction(name => document.querySelector('input[readonly]')?.value === name, teacher.user.name)
  assert.equal(await editor.getByLabel('Учител', { exact: true }).inputValue(), teacher.user.name)
  assert.equal(await editor.getByLabel('Учител', { exact: true }).getAttribute('readonly'), '')
  await editor.getByLabel('Име', { exact: true }).fill('   ')
  assert.equal(await editor.getByRole('button', { name: 'Запази', exact: true }).isDisabled(), true)
  await editor.getByLabel('Име', { exact: true }).fill(renamed)
  await editor.getByLabel('Дисциплина', { exact: true }).fill('Java')
  await editor.getByLabel('Учебна година', { exact: true }).fill('2027/2028')
  await editor.getByLabel('Клас / курс', { exact: true }).fill('12')
  await editor.getByRole('textbox', { name: 'Описание', exact: true }).fill('Updated description')
  await editor.getByRole('combobox', { name: 'Статус', exact: true }).selectOption('archived')
  await page.screenshot({ path: new URL('group-edit-desktop.png', artifacts).pathname, fullPage: true })
  await page.route(`**/api/v1/groups/${group.id}`, route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ detail: 'Неуспешен запис.' }) }), { times: 1 })
  await editor.getByRole('button', { name: 'Запази', exact: true }).click()
  await editor.getByRole('alert').getByText('Неуспешен запис.', { exact: true }).waitFor()
  assert.equal(await editor.getByLabel('Име', { exact: true }).inputValue(), renamed)
  assert.equal((await request('/api/v1/groups', teacher)).data.find(g => g.id === group.id).name, original)
  await editor.getByRole('button', { name: 'Запази', exact: true }).click()
  await editor.waitFor({ state: 'detached' })
  const updated = () => page.getByRole('row').filter({ has: page.getByRole('button', { name: renamed, exact: true }) })
  await updated().getByText('Java', { exact: true }).waitFor()
  const saved = (await request('/api/v1/groups', teacher)).data.find(g => g.id === group.id)
  assert.equal(saved.school_year, '2027/2028')
  assert.equal(saved.class_label, '12')
  assert.equal(saved.description, 'Updated description')
  assert.equal(saved.status, 'archived')
  await page.getByRole('button', { name: renamed, exact: true }).click()
  await participants.getByRole('cell', { name: student.user.email, exact: true }).waitFor()
  await participants.getByRole('button', { name: 'Към групите', exact: true }).click()
  await updated().getByRole('button', { name: 'Изтрий групата', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Изтриване на група' })
  await dialog.waitFor()
  assert.equal((await request('/api/v1/groups', teacher)).data.some(g => g.id === group.id), true)
  await page.screenshot({ path: new URL('group-delete-desktop.png', artifacts).pathname })
  await dialog.getByRole('button', { name: 'Отказ', exact: true }).click()
  await updated().getByRole('button', { name: 'Изтрий групата', exact: true }).click()
  await page.keyboard.press('Escape')
  await dialog.waitFor({ state: 'detached' })
  await page.setViewportSize({ width: 390, height: 844 })
  await updated().getByRole('button', { name: 'Редактирай групата', exact: true }).click()
  await editor.getByLabel('Име', { exact: true }).waitFor()
  assert.equal(await editor.getByLabel('Име', { exact: true }).inputValue(), renamed)
  assert.equal(await editor.getByRole('textbox', { name: 'Описание', exact: true }).inputValue(), 'Updated description')
  await editor.getByLabel('Име', { exact: true }).fill('Do not save')
  await page.getByRole('button', { name: 'Тъмна тема', exact: true }).click()
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
  await page.screenshot({ path: new URL('group-edit-mobile.png', artifacts).pathname, fullPage: true })
  await editor.getByRole('button', { name: 'Към групите', exact: true }).click()
  assert.equal((await request('/api/v1/groups', teacher)).data.find(g => g.id === group.id).name, renamed)
  await updated().getByRole('button', { name: 'Редактирай групата', exact: true }).click()
  assert.equal(await editor.getByLabel('Име', { exact: true }).inputValue(), renamed)
  await editor.getByRole('button', { name: 'Към групите', exact: true }).click()
  await updated().getByRole('button', { name: 'Изтрий групата', exact: true }).click()
  await dialog.getByRole('button', { name: 'Изтрий', exact: true }).click()
  await page.getByText('Групата е изтрита.', { exact: true }).waitFor()
  assert.equal((await request('/api/v1/groups', teacher)).data.some(g => g.id === group.id), false)
  assert.equal((await request('/api/v1/groups', student)).data.some(g => g.id === group.id), false)
  assert.equal((await request(`/api/v1/groups/${group.id}/members`, teacher)).status, 404)
  await page.reload()
  await page.getByRole('button', { name: 'Групи', exact: true }).click()
  await page.getByText('Няма записи.', { exact: true }).waitFor()
  assert.deepEqual(errors, [])
  console.log('Passed: group creation/editing, member removal modal with cancel/Escape/focus, failure/retry, busy protection, no removal before confirmation, persistence, group deletion, desktop/mobile and both themes.')
} finally {
  await browser.close()
}
