import assert from 'node:assert/strict'
import { mkdir } from 'node:fs/promises'
import { chromium } from 'playwright'

const base = process.env.E2E_API_URL ?? 'http://localhost:8080'
const frontend = process.env.E2E_FRONTEND_URL ?? 'http://localhost:5173'
const stamp = Date.now()
async function request(path, auth, method = 'GET', data) {
  const response = await fetch(`${base}${path}`, { method, headers: { 'Content-Type': 'application/json', ...(auth ? { Authorization: `Bearer ${auth.token}` } : {}) }, ...(data === undefined ? {} : { body: JSON.stringify(data) }) })
  assert.equal(response.status, 200)
  const text = await response.text()
  return text ? JSON.parse(text) : null
}
const teacher = await request('/api/auth/register', null, 'POST', { name: 'Library Teacher', email: `library-${stamp}@example.test`, password: 'test-password-123', role: 'TEACHER' })
const other = await request('/api/auth/register', null, 'POST', { name: 'Shared Teacher', email: `shared-library-${stamp}@example.test`, password: 'test-password-123', role: 'TEACHER' })
const definition = text => ({ title: `Library ${text} ${stamp}`, description: '', subject: 'Java', level: '12', instructions: '', language: 'bg', gradingScale: 'bulgarian', passThreshold: 50, questions: [{ type: 'SINGLE_CHOICE', text, difficulty: 'EASY', points: 1, timeSeconds: 30, options: [{ text: 'boolean', correct: true }, { text: 'String', correct: false }], acceptedAnswers: [], caseInsensitive: true, collapseWhitespace: true, criteria: '', explanation: 'A boolean stores true or false.' }] })
const first = await request('/api/v1/tests', teacher, 'POST', definition('First question'))
const second = await request('/api/v1/tests', teacher, 'POST', definition('Second question'))
const shared = await request('/api/v1/tests', other, 'POST', definition('Shared question'))
await request(`/api/v1/tests/${shared.id}/sharing`, other, 'PUT', { shared: true })
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH ?? (process.platform === 'darwin' ? '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' : undefined), headless: true })
const artifacts = new URL('../../.artifacts/', import.meta.url)
await mkdir(artifacts, { recursive: true })
const errors = []
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } })
  await context.addInitScript(value => localStorage.setItem('quicktest.auth', JSON.stringify(value)), teacher)
  const page = await context.newPage()
  page.on('pageerror', error => errors.push(error.message))
  await page.goto(frontend)
  await page.getByRole('button', { name: 'Тестове', exact: true }).click()
  const library = page.getByRole('table', { name: 'Тестове', exact: true })
  await library.getByRole('button', { name: first.title, exact: true }).waitFor()
  assert.equal(await page.getByRole('table', { name: 'Въпроси на избрания тест' }).count(), 0)
  await page.getByRole('button', { name: 'С AI', exact: true }).click()
  const positions = await page.evaluate(() => ({ table: document.querySelector('table[aria-label="Тестове"]').getBoundingClientRect().top, ai: document.querySelector('.ws-ai-band').getBoundingClientRect().top }))
  assert.ok(positions.table < positions.ai)
  const firstRow = library.getByRole('row').filter({ has: page.getByRole('button', { name: first.title, exact: true }) })
  const secondRow = library.getByRole('row').filter({ has: page.getByRole('button', { name: second.title, exact: true }) })
  await firstRow.getByRole('cell').nth(1).click()
  const questions = page.getByRole('table', { name: 'Въпроси на избрания тест' })
  await questions.getByText('First question', { exact: true }).waitFor()
  assert.equal(await library.locator('tr[aria-selected="true"]').count(), 1)
  assert.equal(await library.getByRole('button', { name: first.title, exact: true }).getAttribute('aria-pressed'), 'true')
  assert.equal(await page.getByLabel('Заглавие', { exact: true }).count(), 0)
  await page.route(`**/api/v1/tests/${second.id}`, route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ detail: 'Temporary failure' }) }))
  await library.getByRole('button', { name: second.title, exact: true }).click()
  await page.getByRole('alert').waitFor()
  assert.equal(await questions.getByText('First question', { exact: true }).count(), 1)
  await page.unroute(`**/api/v1/tests/${second.id}`)
  await library.getByRole('button', { name: second.title, exact: true }).click()
  await questions.getByText('Second question', { exact: true }).waitFor()
  assert.equal(await questions.getByText('First question', { exact: true }).count(), 0)
  assert.equal(await library.getByRole('button', { name: second.title, exact: true }).getAttribute('aria-pressed'), 'true')
  for (const column of [0, 2, 3, 4]) {
    await firstRow.getByRole('cell').nth(column).click({ position: { x: 5, y: 5 } })
    await questions.getByText('First question', { exact: true }).waitFor()
    await secondRow.focus()
    await page.keyboard.press(column === 2 ? 'Space' : 'Enter')
    await questions.getByText('Second question', { exact: true }).waitFor()
  }
  let accidentalSelections = 0
  page.on('request', request => { if (request.method() === 'GET' && request.url() === `${base}/api/v1/tests/${first.id}`) accidentalSelections++ })
  await firstRow.getByRole('button', { name: 'Сподели с учителите', exact: true }).click()
  await firstRow.getByRole('button', { name: 'Направи личен', exact: true }).waitFor()
  await firstRow.getByRole('button', { name: 'Направи личен', exact: true }).click()
  await firstRow.getByRole('button', { name: 'Сподели с учителите', exact: true }).waitFor()
  await firstRow.getByRole('button', { name: 'Дублирай', exact: true }).click()
  await library.getByRole('button', { name: `${first.title} (копие)`, exact: true }).waitFor()
  await firstRow.getByRole('button', { name: 'Изтрий / архивирай', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Отказ', exact: true }).click()
  assert.equal(accidentalSelections, 0)
  assert.equal(await questions.getByText('Second question', { exact: true }).count(), 1)
  await page.screenshot({ path: new URL('test-library-desktop.png', artifacts).pathname, fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
  await page.screenshot({ path: new URL('test-library-mobile.png', artifacts).pathname, fullPage: true })
  await page.getByRole('button', { name: 'Редактирай теста', exact: true }).click()
  assert.equal(await page.getByLabel('Заглавие', { exact: true }).inputValue(), second.title)
  await page.getByLabel('Описание', { exact: true }).fill('Edited from preview')
  await page.getByRole('button', { name: 'Запази теста', exact: true }).click()
  await library.waitFor()
  await page.getByText('Тестът е запазен.', { exact: true }).waitFor()
  assert.equal(await library.locator('tr[aria-selected="true"]').count(), 0)
  await library.getByRole('button', { name: shared.title, exact: true }).click()
  await questions.getByText('Shared question', { exact: true }).waitFor()
  assert.equal(await page.getByRole('button', { name: 'Редактирай теста', exact: true }).count(), 0)
  assert.deepEqual(errors, [])
  console.log('Passed: library first, selected row, question preview, switching, fetch failure, owner editing, shared read-only access, desktop/mobile layout.')
} finally {
  await browser.close()
  await request(`/api/v1/tests/${shared.id}/sharing`, other, 'PUT', { shared: false })
}
